# Generated by Django 5.2 on 2025-04-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Allow this note to appear in public listings?"
            ),
        ),
    ]
